### DISCUSSION TITLE
Suborbital Compute @Azure AKS - scc-controlplane-deployment crashloop

### DISCUSSION THREAD

**Discussion by floriankoch** [suborbital/meta#10] [General]
Hi,

i installed suborbital compute to Azure AKS with this documentation
https://docs.suborbital.dev/compute/cloud-deployment/install-compute-in-your-cloud-environment 

It does not work, the controlplane crashloops

How can i debug this? Any hints?

Here are logs from the scc-controlplane-deployment
```
kubectl -n suborbital logs -f scc-controlplane-deployment-765cc68794-7j5z4 -c bu
ilder
⏩ START: downloading templates
✅ DONE: templates downloaded
{"log_message":"(I) configured for HTTPS using domain sub.fko.tmp.cloud.xxx","timestamp":"2022-03-22T07:18:53.297092454Z","level":3,"app":{"scc_version":"0.2.0"}}
{"log_message":"(I) serving TLS challenges on :8080","timestamp":"2022-03-22T07:18:53.297268553Z","level":3,"app":{"scc_version":"0.2.0"}}
{"log_message":"(I) serving on :8443","timestamp":"2022-03-22T07:18:53.297347853Z","level":3,"app":{"scc_version":"0.2.0"}}
2022/03/22 07:19:01 http: TLS handshake error from 10.61.206.6:52538: EOF
2022/03/22 07:19:01 http: TLS handshake error from 10.61.206.4:63724: EOF
2022/03/22 07:19:02 http: TLS handshake error from 10.61.206.5:37644: EOF
2022/03/22 07:19:07 http: TLS handshake error from 10.61.206.6:26891: EOF
2022/03/22 07:19:07 http: TLS handshake error from 10.61.206.4:32400: EOF
2022/03/22 07:19:08 http: TLS handshake error from 10.61.206.5:42812: EOF
```
```
kubectl -n suborbital logs -f scc-controlplane-deployment-765cc68794-7j5z4 -c controlplane
{"log_message":"(W) configured to use HTTP with no TLS","timestamp":"2022-03-22T07:22:17.75614786Z","level":2,"app":{"scc_version":"0.2.0"}}
{"log_message":"(I) [discovery-local] starting discovery, advertising endpoint 8081 /meta/message","timestamp":"2022-03-22T07:22:17.757210459Z","level":3,"app":{"scc_version":"0.2.0"}}
{"log_message":"(I) successfully connected to telemetry","timestamp":"2022-03-22T07:22:18.298404086Z","level":3,"app":{"scc_version":"0.2.0"}}
Error: failed to ResultsManager.Start: failed to db.Exec(sqliteSchema): database is locked
Usage:
  controlplane [flags]

Flags:
  -h, --help      help for controlplane
  -v, --version   version for controlplane
```

**Comment by cohix** [comment]
Thanks for writing in @floriankoch and apologies for the delay - glad you were able to connect with @ospencer. Let us know if anything else comes up, and we'll be sure to post the resolution to this issue in this thread when it is found (I know the team is working on it as we speak).

**Comment by floriankoch** [comment]
@cohix  thank you

@ospencer

I found the problem - i initially choose **azurefiles** as storage class.
Azurefiles is a SMB Share mounted into the Pod

Seems that sqlite can't use SMB , i switched to a traditional Disk - now the pods startiung up

**Reply by cohix** [reply]
Yes we found the same! We also discovered another issue on Azure - AKS networking doesn't play nicely with UDP multicast, which is used to create local connections between services. We experimented with a number of alternative network settings and couldn't find one that works, so we've implemented a workaround and a new version should be available early next week. Sorry for the delay in getting started! Oscar will keep you updated on the new release.

**Comment by ospencer** [comment]
Hey @floriankoch, my apologies again for the delay here! We've implemented a few changes to get everything working on AKS.

To deploy to AKS, you'll need to make two changes to `.suborbital/scc-atmo-deployment.yaml` in your Compute deployment:

- Update the Atmo image version to v0.4.6, found under `containers`.
- Set the `ATMO_PEERS` environment variable to `"scc-controlplane-service.suborbital.svc.cluster.local:8081/meta/message"`, found under `env`.

Once complete, the `spec` key should look like this:
```yaml
spec:
  replicas: 1

  selector:
    matchLabels:
      app: scc-atmo

  template:
    metadata:
      labels:
        app: scc-atmo

    spec:
      containers:
        - name: atmo
          image: suborbital/atmo:v0.4.6
          command: ["atmo"]

          ports:
            - containerPort: 8080

          env:
            - name: ATMO_HTTP_PORT
              value: "8080"

            - name: ATMO_LOG_LEVEL
              value: "info"

            - name: ATMO_CONTROL_PLANE
              value: "scc-controlplane-service:8081"

            - name: ATMO_PEERS
              value: "scc-controlplane-service.suborbital.svc.cluster.local:8081/meta/message"

            - name: ATMO_HEADLESS
              value: "true"
```

Additionally, like you mentioned, you'll need to use the `default` AKS storage class. If you still have Compute deployed, you can update it by running `subo compute deploy core` again or `kubectl apply -f .suborbital/` directly. Otherwise, you can run `subo compute deploy core --dryrun` to scaffold the deployment configuration, make the configuration changes mentioned above, and then run `subo compute deploy core`.

That should have things in working order—let me know if it doesn't!
